// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL_ENV = import.meta.env.VITE_SUPABASE_URL as string | undefined;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY as string;
const SUPABASE_PROJECT_ID = import.meta.env.VITE_SUPABASE_PROJECT_ID as string | undefined;

// Derive URL from anon key (payload.ref) if needed
function getSupabaseUrlFromKey(key: string): string | null {
  try {
    if (!key || typeof key !== 'string') return null;
    const parts = key.split('.');
    if (parts.length !== 3) return null;
    const payload = JSON.parse(atob(parts[1]));
    if (payload?.ref) return `https://${payload.ref}.supabase.co`;
  } catch (_) {
    // ignore
  }
  return null;
}

// Resolve URL in a resilient way
let SUPABASE_URL = SUPABASE_URL_ENV
  || (SUPABASE_PUBLISHABLE_KEY ? getSupabaseUrlFromKey(SUPABASE_PUBLISHABLE_KEY) || undefined : undefined)
  || (SUPABASE_PROJECT_ID ? `https://${SUPABASE_PROJECT_ID}.supabase.co` : undefined);

// Debug log (safe): helps diagnose env loading issues
if (typeof window !== 'undefined') {
  console.info('[Supabase client] URL resolved =', SUPABASE_URL);
}

if (!SUPABASE_PUBLISHABLE_KEY) {
  throw new Error('VITE_SUPABASE_PUBLISHABLE_KEY is required.');
}
if (!SUPABASE_URL) {
  throw new Error('Supabase URL is required. Ensure VITE_SUPABASE_URL or VITE_SUPABASE_PROJECT_ID is set, or the key is valid.');
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
}) as any;
